name: infinite_listview_pagination
description: "A customizable Flutter widget for infinite scrolling lists with optional sticky headers and pull-to-refresh."
version: 0.0.2
homepage: https://github.com/dizayn3r/infinite_listview_pagination.git
repository: https://github.com/dizayn3r/infinite_listview_pagination.git
issue_tracker: https://github.com/dizayn3r/infinite_listview_pagination.git/issues

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  logger: 2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.0
  flutter_lints: ^4.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
