name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.2' # use your target version
          channel: 'stable'

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Run format check
      - name: Check formatting
        run: flutter format --set-exit-if-changed .

      # Run analyzer
      - name: Run analyzer
        run: flutter analyze

      # Run tests
      - name: Run tests
        run: flutter test

      # Pub publish dry-run
      - name: Check pub publish readiness
        run: flutter pub publish --dry-run
